[package]
name = "vec3"
version = "0.1.0"
authors = ["Zheoni <zheoni@outlook.es>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
